### ISSUE TITLE
Actividad 10 corregida: Fallo (ver descripción) 

### ISSUE THREAD

**Issue by cborcar637** [mrampar472/Unidad-3#10]
El código no está bien porque utilizas la estructura array como si fuera una variable primitiva. En otras palabras, para asignar datos al array `notas` no se pone `notas = `, sino que ha de ponerse `notas[posición]`.

Observa como lo haces en el array `alumno`

Si decides arreglar los fallos, escribe aquí para que me llegue la notificación y revisártelo de nuevo.

**Comment by mrampar472** [comment]
Ya lo he corregido

**Comment by cborcar637** [comment]
Revisado
