### ISSUE TITLE
Actividad 8 corregida: Fallo (ver descripción)

### ISSUE THREAD

**Issue by cborcar637** [mrampar472/Unidad-3#7]
El código está bien, pero en la parte del `Switch`, el mensaje lo muestras con un `alert`, y debe mostrarse en el párrafo del HTML, tal y como lo hace la parte del `If`. Es decir, usando el `document.getElementById`... 

Por cierto, Paola y Daisy han entregado la misma solución. No es que lo tengáis igual porque os habéis ayudado, es que es una copia directa. **Me lo tenéis que explicar en clase.**

**Comment by mrampar472** [comment]
Ya la he corregido

**Comment by cborcar637** [comment]
El código no funciona, hay un error en el último `document.getElementBy..` y es que no has cerrado las comillas. Otro fallo es que el switch no toma el valor de la hora del cuadro de texto, sino que se lo pide al usuario mediante un `prompt` y no debería de ser así.

Si decides arreglar los fallos, escribe aquí para que me llegue la notificación y revisártelo de nuevo.

**Comment by mrampar472** [comment]
Ya lo he corregido otra vez

**Comment by cborcar637** [comment]
Revisado
